export const FETCH_INITIAL_LISTINGS = 'FETCH_INITIAL_LISTINGS';
export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const FETCH_RESTAURANT_PROFILE = 'FETCH_RESTAURANT_PROFILE';
export const FETCH_RESTAURANT_MENU = 'FETCH_RESTAURANT_MENU';
export const FETCH_RESTAURANT_REVIEWS = 'FETCH_RESTAURANT_REVIEWS';